### PR TITLE
Slider fixes

### LINKED ISSUE #31: Hue/gradient sliders change color on click
Currently they use the default behaviour for slider, that is scroll in the direction of click, which is pretty counter-intuitive and inconvenient for color choosing. Better behaviour would be to immediately switch to position under mouse cursor (same as color wheel).

### PR DESCRIPTION
**Pull request by caryoscelus**
Several fixes for gradient/hue sliders:

- jump to value on click (fixes #31)
- add colorChanged signal (#30)
- fix vertical hue slider (it was inverted before)

### CODE REVIEW

**Comment by caryoscelus** [comment]
I guess i'll just push fixes here before they i get branches messed up.

**Comment by mbasaglia** [comment]
Just wanted to let you know that I haven't forgotten about this merge request but haven't gotten time to properly review it just yet. Hopefully I'll have some free time this Sunday.

File: src/gradient_slider.cpp [hunk 1]
```diff
@@ -64,7 +66,20 @@ GradientSlider::GradientSlider(Qt::Orientation orientation, QWidget *parent) :
...
 GradientSlider::~GradientSlider()
 {
-	delete p;
+    delete p;
+}
+
+void GradientSlider::mousePressEvent(QMouseEvent *ev)
+{
+    bool vertical = orientation() == Qt::Vertical;
+    bool reverse = vertical != invertedAppearance();
```
Comment (mbasaglia) [inline src/gradient_slider.cpp]: Looks like invertedAppearance appearance isn't fully supported (eg: the gradient slider doesn't invert the gradient) but at least it works so I guess it's OK.

File: src/hue_slider.cpp [hunk 2]
```diff
@@ -129,11 +126,17 @@ void HueSlider::setFullColor(const QColor& color)
 
 qreal HueSlider::colorHue() const
 {
-    return p->percent();
+    auto hue = qreal(value() - minimum()) / (maximum() - minimum());
```
Comment (mbasaglia) [inline src/hue_slider.cpp]: This would result into a division by zero if maximum() == minimum(). I think it's worth having a check here.

Comment (caryoscelus) [reply src/hue_slider.cpp]: Good catch.

Comment (caryoscelus) [reply src/hue_slider.cpp]: On the other hand it doesn't make sense to set max == min. I wonder what hue should slider return then? Previous version has the same /0 behaviour.

I guess we can just return 0 (red) since that would at least match both min and max.

Comment (caryoscelus) [reply src/hue_slider.cpp]: Perhaps the best would be to forbid manually changing min/max at all, but since setters aren't virtual it's not going to work with abstract slider pointers.

Comment (mbasaglia) [reply src/hue_slider.cpp]: I think the easiest way is to have a condition here, returning 0 seems reasonable.

**Comment by caryoscelus** [comment]
I created an issue for inverted appearance - i'll look into it next time i tackle sliders; /0 issue is fixed.
